import { Component, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { forkJoin, of, firstValueFrom } from 'rxjs';
import { catchError } from 'rxjs/operators';
import { ApiService, Business, FinancialEventInput, CreateBusinessInput } from './app.service';

@Component({ selector:'app-root', standalone:true, imports:[CommonModule, FormsModule], templateUrl:'./app.component.html' })
export class AppComponent implements OnInit {
  readonly Math = Math; private api = inject(ApiService);
  businesses: Business[] = []; selected = ''; loading = true; error = ''; dashboard: any; ml: any; events: any[] = []; days = 90;
  saving = false; creating = false; eventNotice = ''; event = { type:'revenue', direction:'inflow' as 'inflow'|'outflow', amount:250000, description:'Customer payment received' };
  scenario = 'growth'; scenarioLoading = false;
  businessForm = { legalName:'', displayName:'', externalId:'', currency:'INR', timezone:'Asia/Kolkata' };
  ngOnInit(): void { this.api.businesses().subscribe({ next:r => { this.businesses=r.data||[]; this.selected=this.businesses[0]?.id||''; this.selected ? this.load() : this.loading=false; }, error:() => { this.error='Unable to load MSMEs'; this.loading=false; } }); }
  load(): void { if(!this.selected) return; this.loading=true; this.error=''; forkJoin({ dashboard:this.api.dashboard(this.selected,this.days).pipe(catchError(()=>of({data:null}))), ml:this.api.ml(this.selected).pipe(catchError(()=>of({data:null}))), events:this.api.events(this.selected).pipe(catchError(()=>of({data:[]}))) }).subscribe(r => { this.dashboard=r.dashboard.data; this.ml=r.ml.data; this.events=r.events.data||[]; this.loading=false; if(!this.dashboard) this.error='Financial state is not available yet. Add an event above to begin building the twin.'; }); }
  submitEvent(): void { if(!this.selected || this.event.amount <= 0) return; this.saving=true; this.eventNotice=''; const input:FinancialEventInput={ type:this.event.type, direction:this.event.direction, amount:Number(this.event.amount), description:this.event.description, source:'lender-dashboard', sourceEventId:`dashboard-${Date.now()}-${Math.random().toString(36).slice(2,7)}`, occurredAt:new Date().toISOString(), currency:this.businesses.find(b=>b.id===this.selected)?.currency||'INR' }; this.api.ingestEvent(this.selected,input).subscribe({ next:() => { this.eventNotice='Event accepted. Updating the digital twin…'; setTimeout(()=>this.load(),1800); this.saving=false; }, error:() => { this.eventNotice='Event could not be submitted. Please retry.'; this.saving=false; } }); }
  syncDirection(): void { this.event.direction = ['revenue','receivable','transaction'].includes(this.event.type) ? 'inflow' : 'outflow'; }
  selectedCurrency(): string { return this.businesses.find(b => b.id === this.selected)?.currency || 'INR'; }
  selectedBusinessName(): string { const business = this.businesses.find(b => b.id === this.selected); return business?.displayName || business?.legalName || 'MSME'; }
  createBusiness(): void { if (!this.businessForm.legalName.trim()) return; this.creating=true; const input:CreateBusinessInput={ ...this.businessForm, externalId:this.businessForm.externalId || undefined, displayName:this.businessForm.displayName || undefined }; this.api.createBusiness(input).subscribe({next:r=>{this.businesses=[r.data,...this.businesses];this.selected=r.data.id;this.businessForm={legalName:'',displayName:'',externalId:'',currency:'INR',timezone:'Asia/Kolkata'};this.creating=false;this.load();},error:()=>{this.creating=false;this.eventNotice='MSME could not be created. Check that the backend is running.';}}); }
  async loadScenario(): Promise<void> { if (!this.selected || this.scenarioLoading) return; this.scenarioLoading=true; this.eventNotice='Creating a 30-day financial history…'; try { const items=this.scenarioEvents(); for (let i=0;i<items.length;i++) { await firstValueFrom(this.api.ingestEvent(this.selected,items[i])); this.eventNotice=`Building demo history: ${i+1} of ${items.length} signals accepted…`; } this.eventNotice='Scenario accepted. The worker is building the twin and analytics now…'; setTimeout(()=>this.load(),3000); } catch { this.eventNotice='Scenario could not be loaded. Please retry.'; } finally { this.scenarioLoading=false; } }
  private scenarioEvents(): FinancialEventInput[] { const patterns:Record<string,{revenue:number;expense:number;repayment:number;receivable:number;label:string}>={ growth:{revenue:185000,expense:72000,repayment:18000,receivable:15000,label:'Growing business'}, stress:{revenue:90000,expense:125000,repayment:42000,receivable:70000,label:'Cash-flow stress'}, recovery:{revenue:150000,expense:82000,repayment:22000,receivable:22000,label:'Recovery trajectory'} }; const p=patterns[this.scenario]; const currency=this.selectedCurrency(); const result:FinancialEventInput[]=[]; for(let day=29;day>=0;day--){ const date=new Date(); date.setDate(date.getDate()-day); const wave=1+((day%5)-2)*.06; const base=`scenario-${this.scenario}-${Date.now()}-${day}`; result.push({type:'revenue',source:'demo-scenario',sourceEventId:`${base}-rev`,occurredAt:date.toISOString(),amount:Math.round(p.revenue*wave),direction:'inflow',currency,description:`${p.label}: customer collections`}); result.push({type:'expense',source:'demo-scenario',sourceEventId:`${base}-exp`,occurredAt:date.toISOString(),amount:Math.round(p.expense*(2-wave)),direction:'outflow',currency,description:`${p.label}: operating expense`}); if(day%7===0) result.push({type:'repayment',source:'demo-scenario',sourceEventId:`${base}-rep`,occurredAt:date.toISOString(),amount:p.repayment,direction:'outflow',currency,description:'Scheduled lender repayment'}); if(day%6===0) result.push({type:'receivable',source:'demo-scenario',sourceEventId:`${base}-rec`,occurredAt:date.toISOString(),amount:p.receivable,direction:'inflow',currency,description:'Invoice raised / receivable recorded'}); } return result; }
}
